name: Starting a new work item

on:
    project_card:
        types: [moved]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Print some variables
              env:
                  GITHUB_EVENT_CONTEXT: ${{ toJson(github.event.changes.column_id.from)}}
                  GITHUB_PROJECT_CARD_CONTEXT: ${{ toJson(github.event.project_card.column_id)}}
              run: |
                  echo "$GITHUB_EVENT_CONTEXT"
                  echo "$GITHUB_PROJECT_CARD_CONTEXT"
            - name: Check move from "TODO" to "IN PROGRESS"
              uses: vazexqi/salesforcedx-kanban-actions/project_card-check-movement@master
              with:
                  fromColumndId: $ {{ github.event.changes.column_id.from}}
                  fromColumnName: TODO
                  toColumnId: $ {{ github.event.project_card.column_id}}
                  toColumnName: IN PROGRESS
            - uses: actions/checkout@v1
            - name: Show environment variables
              shell: bash
              run: |
                  cat $GITHUB_EVENT_PATH
